---
# Playbook to install nagios server and generate hosts/checks
# This also installs NRPE on clients for more in-depth checks based on
# Ansible inventory
# author: Will Foster (@sadsfae)
# https://github.com/sadsfae/ansible-nagios
# https://hobo.house/2016/06/24/automate-nagios-deployment-with-ansible/

- name: Check Operating System
  fail:
    msg="You're not running a supported operating system (ubuntu or debian)"
  when: (ansible_os_family != "Debian") 


- name: apt update 
  apt: update_cache=yes 

- name: Install apache
  apt: name={{ item }} state=present
  become: true
  with_items:
    - apache2 

- name: Setup nagios apache vhost
  copy: src=nagios.conf dest=/etc/apache2/sites-available/
- name: enable vhost apache
  command: a2ensite nagios
- name: Install nagios packages and common plugins
  apt: name={{ item }} state=present
  become: true
  with_items:
    - nagios3
    - nagios3-common
    - nagios3-dbg
    - nagios3-cgi
    - nagios-plugins
    - nagios-plugins-common
    - nagios-nrpe-plugin
- name: Check nagios Users
  stat: path=/etc/nagios3/htpasswd.users
  ignore_errors: true
  register: nagios_user_pwfile_exists

- name: Create empty password file
  command: touch /etc/nagios3/htpasswd.users
  args:
    creates: /etc/nagios3/htpasswd.users
  when: nagios_user_pwfile_exists != 0

- name: Create nagios admin user
  command: htpasswd -b -c /etc/nagios3/htpasswd.users {{nagios_username}} {{nagios_password}}
  ignore_errors: true
  when: nagios_user_pwfile_exists != 0

- name: Create nagios guest user
  command: htpasswd -b /etc/nagios3/htpasswd.users {{nagios_ro_username}} {{nagios_ro_password}}
  when: nagios_create_guest_user

- name: Configure nagios main configuration
  copy: src=nagios.cfg dest=/etc/nagios3/nagios.cfg

- name: Configure nagios localhost monitoring
  copy: src=localhost_nagios2.cfg dest=/etc/nagios3/conf.d/localhost_nagios2.cfg

- name: Create generic nagios services config
  copy: src=services_nagios2.cfg dest=/etc/nagios3/

- name: Create generic nagios groups
  copy: src=hostgroups_nagios2.cfg dest=/etc/nagios3/conf.d/
- name: copy nrpe edited file
  copy: src=check_nrpe.cfg dest=/etc/nagios-plugins/config/



- name: Generate the nagios monitoring templates
  template: src={{ item + ".j2" }}
            dest=/etc/nagios3/conf.d/{{ item }}
  with_items:
    - mysql.cfg
    - postgres.cfg
    - webservers.cfg
   # - servers.cfg
    - commands.cfg
   # - elkservers.cfg
   # - elasticsearch.cfg
  register: nagios_needs_restart

- name: Generate the nagios contact template
  template: src={{ item + ".j2" }}
            dest=/etc/nagios3/conf.d/{{ item }}
  with_items:
    - contacts_nagios2.cfg

- name: Generate the nagios user CGI template
  template: src={{ item + ".j2" }}
            dest=/etc/nagios3/{{ item }}
  with_items:
    - cgi.cfg


# employ lineinfile fix for faulty, shipped nagios systemd service
#- name: Check/fix systemd service file
#  lineinfile: dest=/usr/lib/systemd/system/nagios.service \
#          regexp="^ExecStopPost=" \
#          line="ExecStopPost=/usr/bin/rm -f /var/spool/nagios3/cmd/nagios.cmd /var/log/nagios3/rw/nagios.qh"
#  register: systemd_nagios_changed

# change listening port for http to match group_vars/all.yml
- name: Set HTTP Listen Port
  lineinfile: dest=/etc/apache2/ports.conf \
          regexp="^Listen" \
          line="Listen {{nagios_http_port}}"


#- name: Setup HTTPD service
#  command: systemctl enable httpd.service
#  ignore_errors: true
#  when: nagios_needs_restart !=0

- name: Restart apache2 service
  command: service apache2 restart
  ignore_errors: true
  when: nagios_needs_restart !=0

- name: Restart nagios3 service
  command: service nagios3 restart
  ignore_errors: true
  when: nagios_needs_restart !=0



- name: Display nagios information
  debug:
    msg="You can access nagios at https://{{ansible_fqdn}}/nagios using {{nagios_username}} / {{nagios_password}}"

- name: Display nagios guest information
  debug:
    msg="Guest read only users at https://{{ansible_fqdn}}/nagios using {{nagios_ro_username}} / {{nagios_ro_password}}"

- name: Display user password change information
  debug:
    msg="Run the following to change the nagios password --> htpasswd /etc/nagios3/htpasswd.users nagiosadmin"

