# install and setup NRPE and checks

- name: Check Operating System
  fail:
    msg="You're not running a supported operating system (ubuntu or debian)"
  when: (ansible_os_family != "Debian")

#- debug: msg="-----------debug------------"
#- debug: msg=hostvars[host].[ansible_default_ipv4].address

#- name: apt update
#  apt: update_cache=yes
#  become: true
- name: Install NRPE and Common Plugins
  apt: name={{ item }} state=present
  become: true
  with_items:
    - nagios-nrpe-server
    - nagios-plugins

- name: Setup NRPE client configuration
  become: true 
  template:
    src=nrpe.cfg.j2
    dest=/etc/nagios/nrpe.cfg
#  register: nrpe_needs_restart

- name: copy plugins
  copy: src={{ item }} dest=/usr/lib/nagios/plugins/ owner=root group=root mode="u+rwx,g+rwx,o+rx"
  become: true	
  with_items:
   - check_cpu.sh
   - check_mem.pl
   - check_uptime
   - check_postgres.pl
# register: nrpe_needs_restart
### begin firewall ###
# we need TCP/5666 open
# determine firewall status and take action
# 1) use firewall-cmd if firewalld is utilized
# 2) insert iptables rule if iptables is used




### end firewall settings ###

- name: Start NRPE service
  command: service nagios-nrpe-server restart
  become: true
  ignore_errors: true
 # when: nrpe_needs_restart != 0
