---
#
# Playbook to install nagios server, clients and
# generate service checks based on Ansible inventory
#

# we need to collect facts from all hosts we reference
# https://github.com/ansible/ansible/issues/9260
# we skip switches/oobservers because they normally don't
# have python installed.

#- hosts: all:!switches:!oobservers
#  remote_user: kurgan 
#  tasks: []
# role for nagios clients via NRPE
- hosts: webservers:!switches:!oobservers:!nagios
  remote_user: kurgan
  roles:
    - { role: nagios-client }

# role for nagios server
- hosts: nagios
  remote_user: kurgan 
  become: true 
  roles:
    - { role: nagios }
